fix/update github actions (#351)
- fix github workflow error due to deprecated action versions
- all workflows: use latest major versions of actions
- PR: mkdocs builds in parallel as separate jobs to reduce build time
(to 20min from 30min)
- PR: do not trigger workflow when PR is edited or marked ready for
review

## Error when buildings PRs

> Error: This request has been automatically failed because it uses a
deprecated version of `actions/cache: v4.0.2`.
> Please update your workflow to use v3/v4 of actions/cache to avoid
interruptions.
> Learn more:
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

## PR Todo List

- **Type of Change**: Mark the relevant option(s) with 'x':
  - [ ] System Architecture Change
  - [ ] Node Architecture Change
  - [ ] Tutorial Enhancement
  - [ ] Juvix Types/Package Update
  - [ ] Repository Maintenance
- **PR Management**:
  - [ ] Provide a clear and concise description of the changes.
  - [ ] Link to important pages of the PR preview if available.
- [ ] Add the changelog entry by running the `unclog` command, after
creating
    the PR so that the PR number is taken into account.
  - [ ] Add the appropriate labels to the PR.
  - [ ] Assign the PR to the correct person, typically the author.
- [ ] Set the milestone for the PR, ensuring it aligns with the next
release.
- [ ] Confirm if the PR is ready for review; if not, mark it as a draft.
  - [ ] Ensure the PR title and description are clear and concise.
- [ ] Verify that changes are closely related to the PR title and
description,
    focusing on a single change topic per PR.
- **Grammar Checks**: Ensure that all text in the PR is grammatically
correct.
- **Whitespace**: Verify that there are no unnecessary whitespaces in
the
code. Although, this is may be done automatically by the CI/CD pipeline.